### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Band-hi#1]
![Contrato Inteligente - Gandhi Salazar Cruz](https://user-images.githubusercontent.com/46431649/162842786-20586dd6-4cb9-45d7-8353-86ac86983932.png)

**Comment by AndreLuna6** [comment]
Calificación: 20/20

Partes de una infografía: 4
-Coherencia y pertenencia: 4
-Organización de
la información: 4
-Diseño y
composición de
la infografía: 4
-Creatividad: 4

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
